volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    depends_on:
      - db
      - ethereum

    env_file: .env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  ethereum:
    image: ghcr.io/foundry-rs/foundry:latest
    volumes:
      - ..:/app:cached
    entrypoint: [ "/bin/sh", "/app/evm/scripts/deploy-fixture-and-run.sh" ]

    ports:
      - "8545:8545"
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    env_file: .env


